name: Rust Build, Test, Lint
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  call-rust-base-ci:
    name: Run phylax CI
    uses: phylaxsystems/actions/.github/workflows/rust-base.yaml@main
    with:
      rust-channel: 'nightly'
      require-lockfile: true
      requires-private-deps: true

      feature-sets: '[""]'
    secrets:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
